-- Insertar datos de ejemplo para testing de solicitudes de baja
INSERT INTO solicitudes_baja (
    codigo_solicitud, codigo_equipo, nombre_equipo, marca, modelo, numero_serie,
    ubicacion, responsable, solicitante, tipo_baja, justificacion_tecnica,
    justificacion_economica, valor_recuperable, observaciones, estado
) VALUES 
(
    'SB-2024-001',
    'EQ-2021-456',
    'Monitor de Signos Vitales Phillips MP20',
    'Phillips',
    'MP20',
    'PH-MP20-2021-456',
    'UCI - Cama 3',
    'Dr. Garcia Martinez',
    'Ing. Ana Lopez',
    'obsolescencia_tecnologica',
    'El equipo presenta obsolescencia tecnologica avanzada. Los repuestos ya no estan disponibles en el mercado y la tecnologia ha sido reemplazada por modelos mas eficientes.',
    'El costo de mantenimiento anual ($2,500 USD) supera el 60% del valor actual del equipo. La inversion en reparaciones no es rentable.',
    1500.00,
    'Equipo funcional pero con tecnologia obsoleta. Requiere reemplazo urgente.',
    'pendiente'
),
(
    'SB-2024-002',
    'EQ-2020-789',
    'Ventilador Mecanico Drager V500',
    'Drager',
    'V500',
    'DR-V500-2020-789',
    'UCI - Cama 5',
    'Dr. Carlos Ruiz',
    'Ing. Pedro Morales',
    'fin_vida_util',
    'El equipo sufrio danos irreparables en el sistema de control principal debido a una sobretension electrica. La reparacion requiere reemplazo completo de la placa madre.',
    'El costo de reparacion ($8,500 USD) supera el 80% del valor de un equipo nuevo similar.',
    3200.00,
    'Equipo danado por sobretension. Algunos componentes pueden ser recuperados.',
    'aprobada'
),
(
    'SB-2024-003',
    'EQ-2019-234',
    'Bomba de Infusion Baxter AS50',
    'Baxter',
    'AS50',
    'BX-AS50-2019-234',
    'Hospitalizacion - Piso 2',
    'Enfermera Jefe Maria Santos',
    'Ing. Luis Fernandez',
    'costo_mantenimiento_elevado',
    'Los costos de mantenimiento preventivo y correctivo han aumentado significativamente. El equipo requiere calibracion mensual y reemplazo frecuente de sensores.',
    'Costo anual de mantenimiento: $1,800 USD. Disponibilidad de repuestos limitada con precios incrementados en 40%.',
    800.00,
    'Equipo funcional pero con altos costos operativos.',
    'ejecutada'
),
(
    'SB-2024-004',
    'EQ-2022-567',
    'Electrocardiografo Nihon Kohden ECG-1350',
    'Nihon Kohden',
    'ECG-1350',
    'NK-ECG-1350-2022-567',
    'Cardiologia - Consultorio 1',
    'Dr. Andrea Vasquez',
    'Ing. Miguel Torres',
    'reemplazo_tecnologico',
    'Se ha adquirido nueva tecnologia que reemplaza completamente las funciones de este equipo. El nuevo sistema ofrece mejores caracteristicas diagnosticas.',
    'La nueva tecnologia reduce tiempos de diagnostico en 50% y mejora la precision. Mantener ambos equipos genera costos innecesarios.',
    2800.00,
    'Equipo en perfecto estado pero reemplazado por tecnologia superior.',
    'rechazada'
),
(
    'SB-2024-005',
    'EQ-2018-890',
    'Desfibrilador Physio-Control LIFEPAK 15',
    'Physio-Control',
    'LIFEPAK 15',
    'PC-LP15-2018-890',
    'Urgencias - Trauma 1',
    'Dr. Roberto Mendoza',
    'Ing. Carolina Silva',
    'normativa_vigente',
    'El equipo no cumple con las nuevas normativas IEC 60601-2-4:2023 para desfibriladores. Requiere actualizacion de software y hardware que no esta disponible.',
    'El costo de actualizacion para cumplir normativa ($4,200 USD) representa el 70% del valor de un equipo nuevo certificado.',
    2200.00,
    'Equipo funcional pero no cumple normativas actuales de seguridad.',
    'en_proceso'
);